import Head from "next/head";
import { Inter } from "next/font/google";
import ComingSoon from "@/components/comingsoon/CominSoon";
import { Container, Divider } from "@mui/material";
import Banner from "@/components/Banner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner></Banner>
        <ComingSoon />
        <Divider variant="middle" sx={{ width: "80%" }}></Divider>
      </main>
    </>
  );
}
